### ISSUE TITLE
stackfull cell crash

### ISSUE THREAD

**Issue by samth** [pycket/pycket#292]
Somehow a W_Cell ended up in the wrong place.

```
[1555012144.65] STACKFUL -> CEK : ast ---- (make-struct-type 'weak-intern-table #f 1 0 #f AppRand1083 AppRand1085 #f '(0) #f 'weak-intern-table) : (make-struct-type 'weak-intern-table #f 1 0 #f AppRand1083 AppRand1085 #f '(0) #f 'weak-intern-table)
Traceback (most recent call last):
  File "/home/samth/sw/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 46, in entry_point
    return actual_entry(argv)
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 103, in actual_entry
    racket_entry(names, config, current_cmd_args)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 414, in racket_entry
    gen_expander_zo=gen_expander_zo)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 225, in initiate_boot_sequence
    sysconfig = load_bootstrap_linklets(debug, do_load_regexp=do_load_regexp, gen_expander_zo=gen_expander_zo)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 66, in load_bootstrap_linklets
    load_expander(debug, gen_expander_zo)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 55, in load_expander
    load_bootstrap_linklet("expander", debug, is_it_expander=True, generate_zo=generate_zo)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 45, in load_bootstrap_linklet
    _instance, sys_config = load_inst_linklet_json(linklet_file_path, debug, set_version=is_it_expander, generate_zo=generate_zo)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 87, in load_inst_linklet_json
    linkl_instance = instantiate_linklet.call_interpret([linkl, w_null, w_false, w_false])
  File "/home/samth/sw/pycket/pycket/base.py", line 81, in call_interpret
    return interpret_one(ast, env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2665, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2622, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 1110, in interpret
    return w_callable.call_with_extra_info(args_w, env, cont, self)
  File "/home/samth/sw/pycket/pycket/values.py", line 1428, in call_with_extra_info
    return self.code(args, env, cont, extra_call_info)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 269, in remove_extra_info
    return func(*args)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 237, in func_error_handling
    return func_arg_unwrap(*args)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 189, in func_arg_unwrap
    return func(*typed_args)
  File "/home/samth/sw/pycket/pycket/prims/struct_structinfo.py", line 118, in do_make_struct_type
    guard, constr_name, env, cont)
  File "/home/samth/sw/pycket/pycket/values_struct.py", line 84, in make
    return w_struct_type.initialize_props(props, proc_spec, env, cont)
  File "/home/samth/sw/pycket/pycket/values_struct.py", line 204, in initialize_props
    self.initialize_prop(props, p)
  File "/home/samth/sw/pycket/pycket/values_struct.py", line 167, in initialize_prop
    prop = p.car()
AttributeError: 'W_Cell' object has no attribute 'car'
> /home/samth/sw/pycket/pycket/values_struct.py(167)initialize_prop()
-> prop = p.car()
(Pdb) 
```

**Comment by samth** [comment]
This is from just running pycket in the interpreter with no arguments.

**Comment by cderici** [comment]
@samth Yeah I think this is a double wrapping caused by https://github.com/pycket/pycket/commit/da99c2913af2066681828166cca8f8e2939a6d0a, I'll take a closer look
